//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе Приложение.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_of_exercise
    {
        public int id_exercise { get; set; }
        public Nullable<int> id_client { get; set; }
        public string name_exercise { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> repetition { get; set; }
    
        public virtual user user { get; set; }
    }
}
