//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе Приложение.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GYMEntities8 : DbContext
    {
        public GYMEntities8()
            : base("name=GYMEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<list_of_exercise> list_of_exercise { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<subscription> subscriptions { get; set; }
        public virtual DbSet<subscriptionClient> subscriptionClients { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<trener> treners { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<visit_log> visit_log { get; set; }
    }
}
