//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе Приложение.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subscription()
        {
            this.subscriptionClients = new HashSet<subscriptionClient>();
        }
    
        public int id_subscription { get; set; }
        public string discription_subscription { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.TimeSpan> time_start { get; set; }
        public Nullable<System.TimeSpan> time_end { get; set; }

        public string StaffControlsVisibility
        {
            get
            {
                if (App.currentUser.role == 1)
                {
                    return "Collapsed";
                }
                else
                {
                    return "Visible";
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscriptionClient> subscriptionClients { get; set; }
    }
}
