//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе Приложение.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.list_of_exercise = new HashSet<list_of_exercise>();
            this.subscriptionClients = new HashSet<subscriptionClient>();
            this.visit_log = new HashSet<visit_log>();
        }
    
        public int id_user { get; set; }
        public string surname { get; set; }
        public string firstname { get; set; }
        public string patronymic { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<double> weight { get; set; }
        public string password { get; set; }
        public byte[] userImage { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> trener { get; set; }

        public string StaffControlsVisibility
        {
            get
            {
                if (App.currentUser.role == 2)
                {
                    return "Collapsed";
                }
                else
                {
                    return "Visible";
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_of_exercise> list_of_exercise { get; set; }
        public virtual role role1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscriptionClient> subscriptionClients { get; set; }
        public virtual trener trener1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit_log> visit_log { get; set; }
    }
}
